apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-test-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diplom-test-app
  template:
    metadata:
      labels:
        app: diplom-test-app
    spec:
      containers:
        - name: diplom-test-app
          image: loveyourvoice/diplom-test-app:latest
          ports:
            - containerPort: 80