name: Build, Push, and Deploy

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build_and_push:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_LOGIN }}/diplom-test-app:${{ github.ref_name }}

  deploy:
    name: Deploy app to Kubernetes
    runs-on: ubuntu-latest
    needs: build_and_push
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Kubernetes deployment file
        run: |
          sed -i "s|image: .*:.*|image: ${{ secrets.DOCKERHUB_LOGIN }}/diplom-test-app:${{ github.ref_name }}|g" ./k8s-deploy.yaml

      - name: Log in to Kubernetes cluster
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./k8s-deploy.yaml -n default